FROM docker.io/node:18-alpine as base
WORKDIR /app
RUN apk add --no-cache git fish
RUN sed -i -e "s/bin\/ash/bin\/fish/" /etc/passwd
RUN npm install -g npm@latest
ENTRYPOINT [ "/bin/sh", "--login", "-c", "--" ]
CMD [ "while true; do sleep 30; done;" ]